<?php

/**
 * HiPay Fullservice Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache 2.0 Licence
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @author Kassim Belghait <kassim@sirateck.com>
 * @copyright Copyright (c) 2016 - HiPay
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache 2.0 Licence
 * @link https://github.com/hipay/hipay-fullservice-sdk-magento2
 *
 */

/** @var \HiPay\FullserviceMagento\Block\Card\Customerr\ListCard $block */
/** @var \Magento\Framework\Escaper $escaper */
?>


<?php if ($block->getCards() && count($block->getCards())): ?>
    <div class="table-wrapper cards">
        <table class="data table table-cards" id="my-cards-table">
            <caption class="table-caption">
                <?= $escaper->escapeHtml(__('Credit cards')) ?>
            </caption>
            <thead>
            <tr>
                <th scope="col" class="col item">
                    <?= $escaper->escapeHtml(__('Card name')) ?>
                </th>
                <th scope="col" class="col item">
                    <?= $escaper->escapeHtml(__('Exp. Date')) ?>
                </th>
                <th scope="col" class="col item">
                    <?= $escaper->escapeHtml(__('Card Number')) ?>
                </th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($block->getCards() as $_card): ?>
                <tr>
                    <td data-th="<?= $escaper->escapeHtml(__('Card name')) ?>" class="col item">
                        <?= $escaper->escapeHtml($_card->getName()) ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__('Exp. Date')) ?>" class="col item">
                        <?= $escaper->escapeHtml($_card->getCcExpMonth()) ?>
                        /<?= $escaper->escapeHtml($_card->getCcExpYear()) ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__('Card Number')) ?>" class="col item">
                        <?= $escaper->escapeHtml($_card->getCcNumberEnc()) ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a class="action delete remove" role="delete-card" href="#"
                           data-card="<?= $escaper->escapeHtmlAttr($_card->getCardId()) ?>">
                            <span><?= $escaper->escapeHtml(__('Delete')) ?></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?php if ($block->getToolbarHtml()): ?>
        <div class="toolbar products-cards-toolbar bottom">
            <?= $escaper->escapeHtml($block->getToolbarHtml()) ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty">
        <span><?= $escaper->escapeHtml(__('You have recorded no cards.')) ?></span>
    </div>
<?php endif; ?>

<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
            <span><?= $escaper->escapeHtml(__('Back')) ?></span>
        </a>
    </div>
</div>

<script type="text/x-magento-init">
    {
        ".page-main": {
            "card": {
                "deleteCard": "table.table-cards a[role='delete-card']",
                "deleteUrlPrefix": "<?= $escaper->escapeJs($block->getDeleteCardLink()) ?>id/"
        }
    }
}
</script>
    {
        ".page-main": {
            "card": {
                "deleteCard": "table.table-cards a[role='delete-card']",
                "deleteUrlPrefix": "<?= $escaper->escapeJs($block->getDeleteCardLink()) ?>id/"
        }
    }
}
</script>
