<?php

/*
 * HiPay fullservice SDK
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache 2.0 Licence
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @copyright      Copyright (c) 2016 - HiPay
 * @license        http://www.apache.org/licenses/LICENSE-2.0 Apache 2.0 Licence
 *
 */

// @codingStandardsIgnoreFile
/**
 * @var \HiPay\FullserviceMagento\Block\Redirect\Pending $block
 */
?>
<?php
    echo $this
        ->getLayout()
        ->createBlock('HiPay\FullserviceMagento\Block\ExternalJS')
        ->setTemplate('HiPay_FullserviceMagento::additional/external_js.phtml')
        ->toHtml()
?>
<div class="page-title">
    <h1><?php /* @escapeNotVerified */ echo __('Your payment is in pending.') ?></h1>
</div>

<?php if ($block->getRealOrderId()) : ?><p>
    <?php /* @escapeNotVerified */ echo __('Order #') . $block->getRealOrderId() ?></p><?php endif ?>
<?php if ($error = $block->getErrorMessage()) : ?><p><?php /* @escapeNotVerified */ echo $error ?></p><?php endif ?>
<?php if ($referenceToPay = $block->getReferenceToPay()) : ?>
    <style>
        @media print {
            body * {
                visibility: hidden;
            }
            #referenceToPay,
            #referenceToPay * {
                visibility: visible;
            }
        }
    </style>
    <div class="referenceContainer">
        <div id="referenceToPay"></div>
        <button class="action primary checkout print" onclick="window.print()"><?php echo __("PRINT") ?></button>
    </div>
    <script type="text/javascript">
        var lang = '<?php echo $block->getLang() ?>';
        var hipaySdk = new HiPay({
            username: 'hosted',
            password: 'hosted',
            environment: 'production',
            lang: lang.length > 2 ? lang.substr(0, 2) : 'en'
        });
        <?php if($referenceToPay['method'] === 'multibanco') : ?>
            hipaySdk.createReference('multibanco', {
                selector: 'referenceToPay',
                reference: '<?php echo $referenceToPay['reference'] ?>',
                entity: '<?php echo $referenceToPay['entity'] ?>',
                amount: '<?php echo $referenceToPay['amount'] ?>',
                expirationDate: '<?php echo $referenceToPay['expirationDate'] ?>',
            });
        <?php else : ?>
            hipaySdk.createReference('sisal', {
                selector: 'referenceToPay',
                reference: '<?php echo $referenceToPay['reference'] ?>',
                barCode: '<?php echo $referenceToPay['barCode'] ?>'
            });
        <?php endif ?>
    </script>
<?php endif ?>
<p><?php /* @escapeNotVerified */ echo __('Click <a href="%1">here</a> to continue shopping.', $block->escapeUrl($block->getContinueShoppingUrl())) ?>
</p>
