<?php
/**
 * HiPay Fullservice SDK
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache 2.0 Licence
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @category   HiPay
 * @package    HiPay_FullserviceMagento
 * @copyright  Copyright (c) 2016 - HiPay
 * @license    http://www.apache.org/licenses/LICENSE-2.0 Apache 2.0 Licence
 *
 * @var \HiPay\FullserviceMagento\Block\Redirect\Pending $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<?= // Render external JS block safely
 $block
        ->getLayout()
        ->createBlock(\HiPay\FullserviceMagento\Block\ExternalJS::class)
        ->setTemplate('HiPay_FullserviceMagento::additional/external_js.phtml')
        ->toHtml();
?>

<div class="page-title">
    <h1><?= $escaper->escapeHtml(__('Your payment is in pending.')) ?></h1>
</div>

<?php if ($block->getRealOrderId()): ?>
    <p>
        <?= $escaper->escapeHtml(__('Order #')) ?>
        <?= $escaper->escapeHtml($block->getRealOrderId()) ?>
    </p>
<?php endif; ?>

<?php if ($error = $block->getErrorMessage()): ?>
    <p><?= $escaper->escapeHtml($error) ?></p>
<?php endif; ?>

<?php if ($referenceToPay = $block->getReferenceToPay()): ?>
    <style>
        @media print {
            body * {
                visibility: hidden;
            }
            #referenceToPay,
            #referenceToPay * {
                visibility: visible;
            }
        }
    </style>
    <div class="referenceContainer">
        <div id="referenceToPay"></div>
        <button
                class="action primary checkout print"
                type="button"
                onclick="window.print()"
        >
            <?= $escaper->escapeHtml(__('PRINT')) ?>
        </button>
    </div>

    <?php
    $lang = $escaper->escapeJs($block->getLang());
    $method = $escaper->escapeJs($referenceToPay['method']);
    $reference = $escaper->escapeJs($referenceToPay['reference']);
    $entity = isset($referenceToPay['entity']) ? $escaper->escapeJs($referenceToPay['entity']) : '';
    $amount = isset($referenceToPay['amount']) ? $escaper->escapeJs($referenceToPay['amount']) : '';
    $expirationDate = isset($referenceToPay['expirationDate'])
            ? $escaper->escapeJs($referenceToPay['expirationDate'])
            : '';
    $barCode = isset($referenceToPay['barCode']) ? $escaper->escapeJs($referenceToPay['barCode']) : '';
    ?>

    <script>
        var lang = '<?= /* @noEscape */ $lang ?>';
        var hipaySdk = new HiPay({
            username: 'hosted',
            password: 'hosted',
            environment: 'production',
            lang: lang.length > 2 ? lang.substr(0, 2) : 'en'
        });

        <?php if ($referenceToPay['method'] === 'multibanco'): ?>
        hipaySdk.createReference('multibanco', {
            selector: 'referenceToPay',
            reference: '<?= /* @noEscape */ $reference ?>',
            entity: '<?= /* @noEscape */ $entity ?>',
            amount: '<?= /* @noEscape */ $amount ?>',
            expirationDate: '<?= /* @noEscape */ $expirationDate ?>'
        });
        <?php else: ?>
        hipaySdk.createReference('sisal', {
            selector: 'referenceToPay',
            reference: '<?= /* @noEscape */ $reference ?>',
            barCode: '<?= /* @noEscape */ $barCode ?>'
        });
        <?php endif; ?>
    </script>
<?php endif; ?>

<p>
    <?= $escaper->escapeHtml(
        __(
            'Click <a href="%1">here</a> to continue shopping.',
            $escaper->escapeUrl($block->getContinueShoppingUrl())
        )
    ) ?>
</p>
