apiVersion: v1
kind: Service
metadata:
  name: magento2-elastic-{{ .Release.Name }}
  labels:
    app: magento2-{{ .Release.Name }}
    cd-hipay: cron-delete
spec:
  ports:
    - port: 9202
  selector:
    app: magento2-{{ .Release.Name }}
    tier: elastic-{{ .Release.Name }}
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-pv-claim-{{ .Release.Name }}
  labels:
    app: magento2-{{ .Release.Name }}
    cd-hipay: cron-delete
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento2-elastic-{{ .Release.Name }}
  labels:
    app: magento2-{{ .Release.Name }}
    cd-hipay: cron-delete
spec:
  selector:
    matchLabels:
      app: magento2-{{ .Release.Name }}
      tier: elastic-{{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: magento2-{{ .Release.Name }}
        tier: elastic-{{ .Release.Name }}
        cd-hipay: cron-delete
    spec:
      containers:
      - image: {{ .Values.elastic_image }}:{{ .Values.elastic_tag }}
        name: elastic-{{ .Release.Name }}
        resources:
          requests:
            memory: "2G"
            cpu: "500m"
          limits:
            memory: "2.5G"
            cpu: "1000m"
        envFrom:
          - configMapRef:
              name: magento2-configmap-{{ .Release.Name }}
        ports:
          - containerPort: 9202
            name: elastic
      volumes:
        - name: elastic-persistent-storage-{{ .Release.Name }}
          persistentVolumeClaim:
            claimName: elastic-pv-claim-{{ .Release.Name }}
      nodeSelector:
        node_type: default
      tolerations:
        - key: cd_service
          operator: Equal
          value: only
          effect: NoExecute
