<?php 
/**
 * HiPay Fullservice Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache 2.0 Licence
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @copyright      Copyright (c) 2016 - HiPay
 * @license        http://www.apache.org/licenses/LICENSE-2.0 Apache 2.0 Licence
 *
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magento\Payment\Block\Transparent\Form $block
 */
$code = $block->escapeHtml($block->getMethodCode());
?>
<fieldset class="fieldset payment items <?php /* @noEscape */ echo $code; ?>"
          id="payment_form_<?php /* @noEscape */ echo $code; ?>" style="display: none;">
          
          <?php echo $block->escapeHtml( __('You will be redirect to payment page after submit order.')) ?>
          
</fieldset>