<?php
/**
 * HiPay Fullservice Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache 2.0 Licence
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @author Kassim Belghait <kassim@sirateck.com>
 * @copyright Copyright (c) 2016 - HiPay
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache 2.0 Licence
 * @link https://github.com/hipay/hipay-fullservice-sdk-magento2
 *
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $escaper \Magento\Framework\Escaper
 */

$_element = $block->getElement();
?>
<input type="hidden"
       value="<?= $escaper->escapeHtmlAttr($_element->getRule()->getId()) ?>"
       name="<?= $escaper->escapeHtmlAttr($_element->getName()) ?>" />
<div class="rule-tree">
    <fieldset
            id="<?= $escaper->escapeHtmlAttr($_element->getHtmlId()) ?>"
            <?= /* @noEscape */ $_element->serialize(['class']) ?>
            class="fieldset"
    >
        <legend class="legend">
            <span><?= $escaper->escapeHtml($_element->getLegend()) ?></span>
        </legend>
        <br>
        <?php if ($_element->getComment()): ?>
            <div class="messages">
                <div class="message message-notice">
                    <?= $escaper->escapeHtml($_element->getComment()) ?>
                </div>
            </div>
        <?php endif; ?>
        <div class="rule-tree-wrapper">
            <?php if ($_element->getRule() && $_element->getRule()->getConditions()): ?>
                <?= /* @noEscape */ $_element->getRule()->getConditions()->asHtmlRecursive() ?>
            <?php endif; ?>
        </div>
    </fieldset>
</div>
<script>
    require([
        "HiPay_FullserviceMagento/js/rules",
        "prototype"
    ], function(VarienRulesForm){
        window.<?= $escaper->escapeJs($_element->getHtmlId()) ?> = new VarienRulesForm(
            '<?= $escaper->escapeJs($_element->getHtmlId()) ?>',
            '<?= $escaper->escapeUrl($block->getNewChildUrl()) ?>'
        );
        <?php if ($_element->getReadonly()): ?>
            <?= $escaper->escapeJs($_element->getHtmlId()) ?>.setReadonly(true);
        <?php endif; ?>
    });
</script>