<?php

/**
 * HiPay Fullservice Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache 2.0 Licence
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @author Kassim Belghait <kassim@sirateck.com>
 * @copyright Copyright (c) 2016 - HiPay
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache 2.0 Licence
 * @link https://github.com/hipay/hipay-fullservice-sdk-magento2
 *
 */

// @codingStandardsIgnoreFile
/**
 * @var \HiPay\FullserviceMagento\Block\Cc\Form $block
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 * @var $escaper \Magento\Framework\Escaper
 */
$code = $escaper->escapeHtml($block->getMethodCode());
$ccType = $block->getInfoData('cc_type');
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');

$formData = [
        "code" => $code,
        "env" => $block->getEnv(),
        'apiUsername' => $block->getApiUsername(),
        'apiPassword' => $block->getApiPassword(),
        'sdkJsUrl' => $block->getSdkJsUrl()
];

$serializedFormData = $block->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($formData);

?>
<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?= /* @noEscape */ $code; ?>"
          style="display:none"
          data-mage-init='{"fullserviceCcForm":<?= /* @noEscape */ $serializedFormData; ?>}'>

    <input type="hidden"
           name="payment[card_token]"
           id="<?= /* @noEscape */ $code; ?>_card_token"
           value="" />
    <input type="hidden"
           name="payment[eci]"
           id="<?= /* @noEscape */ $code; ?>_eci"
           value="1" />

    <div class="field-number admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code; ?>_cc_owner">
            <span><?= $escaper->escapeHtml(__('Card Owner Name')); ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text"
                   id="<?= /* @noEscape */ $code; ?>_cc_owner"
                   name="payment[cc_owner]"
                   title="<?= $escaper->escapeHtml(__('Card Owner Name')); ?>"
                   class="input-text admin__control-text"
                   value="<?= /* @noEscape */ $block->getInfoData('cc_owner'); ?>"
            />
        </div>
    </div>
    <div class="field-type admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code; ?>_cc_type">
            <span><?= $escaper->escapeHtml(__('Credit Card Type')); ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code; ?>_cc_type"
                    name="payment[cc_type]"
                    class="required-entry _required select validate-cc-type-select admin__control-select">
                <option value=""></option>
                <?php foreach ($block->getCcAvailableTypes() as $typeCode => $typeName): ?>
                    <option value="<?= $escaper->escapeHtml($typeCode); ?>"
                            <?php if ($typeCode == $ccType): ?>
                                selected="selected"
                            <?php endif ?>>
                        <?= $escaper->escapeHtml($typeName); ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <div class="field-number admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code; ?>_cc_number">
            <span><?= $escaper->escapeHtml(__('Credit Card Number')); ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text"
                   id="<?= /* @noEscape */ $code; ?>_cc_number"
                   name="payment[cc_number]"
                   title="<?= $escaper->escapeHtml(__('Credit Card Number')); ?>"
                   class="input-text admin__control-text validate-cc-number validate-cc-type"
                   value="<?= /* @noEscape */ $block->getInfoData('cc_number'); ?>"
                   data-validate='{
                       "required-number":true,
                       "validate-cc-number":"#<?= /* @noEscape */ $code; ?>_cc_type",
                       "validate-cc-type":"#<?= /* @noEscape */ $code; ?>_cc_type"
                   }'
            />
        </div>
    </div>
    <div class="field-date admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code; ?>_expiration">
            <span><?= $escaper->escapeHtml(__('Expiration Date')); ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_expiration"
                    name="payment[cc_exp_month]"
                    class="admin__control-select admin__control-select-month validate-cc-exp required-entry">
                <?php foreach ($block->getCcMonths() as $k => $v): ?>
                    <option value="<?= $escaper->escapeHtml($k); ?>"
                            <?php if ($k == $ccExpMonth): ?>
                                selected="selected"
                            <?php endif ?>>
                        <?= $escaper->escapeHtml($v); ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <select id="<?= /* @noEscape */ $code ?>_expiration_yr"
                    name="payment[cc_exp_year]"
                    class="admin__control-select admin__control-select-year required-entry">
                <?php foreach ($block->getCcYears() as $k => $v): ?>
                    <option value="<?= /* @noEscape */ $k ? $escaper->escapeHtml($k) : '' ?>"
                            <?php if ($k == $ccExpYear): ?>
                                selected="selected"
                            <?php endif ?>>
                        <?= $escaper->escapeHtml($v); ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>

    <?php if ($block->hasVerification()): ?>
        <div class="field-number required admin__field _required">
            <label class="admin__field-label"
                   for="<?= /* @noEscape */ $code; ?>_cc_cid">
                <span><?= $escaper->escapeHtml(__('Card Verification Number')); ?></span>
            </label>
            <div class="admin__field-control">
                <input type="text"
                       title="<?= $escaper->escapeHtml(__('Card Verification Number')); ?>"
                       class="validate-cc-cvn admin__control-cvn admin__control-text"
                       id="<?= /* @noEscape */ $code; ?>_cc_cid"
                       name="payment[cc_cid]"
                       value="<?= /* @noEscape */ $block->getInfoData('cc_cid') ?>"/>
            </div>
        </div>
    <?php endif; ?>

    <?php if ($block->hasSsCardType()): ?>
        <div id="<?= /* @noEscape */ $code; ?>_cc_type_ss_div">
            <div class="field-type required admin__field _required">
                <label class="admin__field-label"
                       for="<?= /* @noEscape */ $code; ?>_cc_issue">
                    <span><?= $escaper->escapeHtml(__('Switch/Solo/Maestro Only')); ?></span>
                </label>
            </div>
            <div class="admin__field field-issue">
                <label class="admin__field-label"
                       for="<?= /* @noEscape */ $code; ?>_cc_issue">
                    <span><?= $escaper->escapeHtml(__('Issue Number')); ?></span>
                </label>

                <div class="admin__field-control">
                    <input type="text"
                           title="<?= $escaper->escapeHtml(__('Issue Number')); ?>"
                           class="validate-cc-ukss cvv admin__control-cvv admin__control-text"
                           id="<?= /* @noEscape */ $code; ?>_cc_issue"
                           name="payment[cc_ss_issue]"
                           value=""/>
                </div>
            </div>
            <div class="field field-date">
                <label class="admin__field-label"
                       for="<?= /* @noEscape */ $code; ?>_start_month">
                    <span><?= $escaper->escapeHtml(__('Start Date')); ?></span>
                </label>
                <div class="admin__field-control">
                    <select id="<?= /* @noEscape */ $code; ?>_start_month"
                            name="payment[cc_ss_start_month]"
                            class="validate-cc-ukss admin__control-select admin__control-select-month">
                        <?php foreach ($block->getCcMonths() as $k => $v): ?>
                            <option value="<?= /* @noEscape */ $k ? $escaper->escapeHtml($k) : '' ?>"
                                    <?php if ($k == $block->getInfoData('cc_ss_start_month')): ?>
                                        selected="selected"
                                    <?php endif ?>>
                                <?= $escaper->escapeHtml($v); ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                    <select id="<?= /* @noEscape */ $code; ?>_start_year"
                            name="payment[cc_ss_start_year]"
                            class="validate-cc-ukss admin__control-select admin__control-select-year">
                        <?php foreach ($block->getSsStartYears() as $k => $v): ?>
                            <option value="<?= /* @noEscape */ $escaper->escapeHtml($k) ? $k : '' ?>"
                                    <?php if ($k == $block->getInfoData('cc_ss_start_year')): ?>
                                        selected="selected"
                                    <?php endif ?>>
                                <?= $escaper->escapeHtml($v); ?>
                            </option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>

            <div class="adv-container">&nbsp;</div>

            <script>
                require(['jquery', 'prototype'], function(jQuery){

                    //<![CDATA[
                    SSChecked<?= /* @noEscape */ $code; ?> = function() {
                        var elm = $('<?= /* @noEscape */ $code; ?>_cc_type');
                        if (['SS','SM','SO'].indexOf(elm.value) != -1) {
                            jQuery('#' + '<?= /* @noEscape */ $code; ?>_cc_type_ss_div')
                                .show()
                                .removeClass('ignore-validate');
                        } else {
                            jQuery('#' + '<?= /* @noEscape */ $code; ?>_cc_type_ss_div')
                                .hide()
                                .addClass('ignore-validate');
                        }
                    };
                    Event.observe(
                        $('<?= /* @noEscape */ $code; ?>_cc_type'),
                        'change',
                        SSChecked<?= /* @noEscape */ $code; ?>
                    );
                    SSChecked<?= /* @noEscape */ $code; ?>();
                    //]]>

                });
            </script>
        </div>
    <?php endif; ?>
</fieldset>