<?php

/**
 * HiPay Fullservice Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache 2.0 Licence
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @author Kassim Belghait <kassim@sirateck.com>
 * @copyright Copyright (c) 2016 - HiPay
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache 2.0 Licence
 * @link https://github.com/hipay/hipay-fullservice-sdk-magento2
 *
 */

// @codingStandardsIgnoreFile
/**
 * @var Form $block
 * @var Escaper $escaper
 */

use HiPay\FullserviceMagento\Block\Hosted\Form;
use Magento\Framework\Escaper;

$code = $escaper->escapeHtml($block->getMethodCode());
?>
<fieldset class="fieldset payment items <?= /* @noEscape */ $code; ?>"
          id="payment_form_<?= /* @noEscape */ $code; ?>" style="display: none;">
    <input type="hidden" name="payment[eci]" id="<?= /* @noEscape */ $code; ?>_eci" value="1"/>
    <?php if ($block->isSendMailToCustomer()): ?>
        <?= $escaper->escapeHtml(__('An email with a payment link will be sent to the customer.')) ?>
    <?php else: ?>
        <?= $escaper->escapeHtml(__('You will be redirect to payment page after submit order.')) ?>
    <?php endif; ?>
</fieldset>
