<?php
/*
 * HiPay fullservice SDK
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @copyright      Copyright (c) 2016 - HiPay
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 *
 */

// @codingStandardsIgnoreFile
/** @var \HiPay\FullserviceMagento\Block\Card\Customerr\ListCard $block */
?>
<?php if ($block->getCards() && count($block->getCards())): ?>
    <div class="table-wrapper cards">
        <table class="data table table-cards" id="my-cards-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Credit cards') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col item"><?php /* @escapeNotVerified */ echo __('Card name') ?></th>
                    <th scope="col" class="col item"><?php /* @escapeNotVerified */ echo __('Exp. Date') ?></th>
                    <th scope="col" class="col item"><?php /* @escapeNotVerified */ echo __('Card Number') ?></th>

                    <th scope="col" class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
            	<?php /** @var $_card \HiPay\FullserviceMagento\Model\Card */  ?>
                <?php foreach ($block->getCards() as $_card): ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Card name')) ?>" class="col item"><?php /* @escapeNotVerified */ echo $block->escapeHtml($_card->getName()) ?></td>
  					<td data-th="<?php echo $block->escapeHtml(__('Exp. Date')) ?>" class="col item"><?php /* @escapeNotVerified */ echo $block->escapeHtml($_card->getCcExpMonth()) . "/" . $block->escapeHtml($_card->getCcExpYear())  ?></td>
					<td data-th="<?php echo $block->escapeHtml(__('Card Number')) ?>" class="col item"><?php /* @escapeNotVerified */ echo $block->escapeHtml($_card->getCcNumberEnc()) ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getDeleteCardLink() ?>id/<?php /* @escapeNotVerified */ echo $_card->getCardId() ?>" class="action delete remove">
                            <span><?php /* @escapeNotVerified */ echo __('Delete') ?></span>
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getToolbarHtml()): ?>
        <div class="toolbar products-cards-toolbar bottom">
            <?php echo $block->getToolbarHtml() ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have recorded no cards.') ?></span></div>
<?php endif; ?>
<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>">
            <span><?php /* @escapeNotVerified */ echo __('Back') ?></span>
        </a>
    </div>
</div>
