<script type="text/javascript">
    require([], function () {
        window.hipayConfig = {
            getApiUsernameTokenJs:
                '<?= $escaper->escapeHtml($block->getApiUsernameTokenJs()) ?>',
            getApiPasswordTokenJs:
                '<?= $escaper->escapeHtml($block->getApiPasswordTokenJs()) ?>',
            getEnv: '<?= $escaper->escapeHtml($block->getEnv()) ?>'
        }
    })
</script>