<?php

/**
 * @var HipayConfig $block
 * @var Escaper $escaper
 */

use HiPay\FullserviceMagento\Block\Adminhtml\HipayConfig;
use Magento\Framework\Escaper;

?>
<script>
    require([], function () {
        window.hipayConfig = {
            getApiUsernameTokenJs:
                '<?= $escaper->escapeHtml($block->getApiUsernameTokenJs()) ?>',
            getApiPasswordTokenJs:
                '<?= $escaper->escapeHtml($block->getApiPasswordTokenJs()) ?>',
            getEnv: '<?= $escaper->escapeHtml($block->getEnv()) ?>'
        }
    })
</script>