<?php

/**
 * HiPay Fullservice Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache 2.0 Licence
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * @author Kassim Belghait <kassim@sirateck.com>
 * @copyright Copyright (c) 2016 - HiPay
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache 2.0 Licence
 * @link https://github.com/hipay/hipay-fullservice-sdk-magento2
 *
 */

// @codingStandardsIgnoreFile

/**
 * @var Form $block
 * @var Escaper $escaper
 */

use Magento\Framework\Escaper;
use Magento\Payment\Block\Transparent\Form;

$code = $escaper->escapeHtml($block->getMethodCode());
$ccType = $block->getInfoData('cc_type');
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');
?>
<fieldset class="fieldset payment items ccard <?= /* @noEscape */
$code; ?>"
          id="payment_form_<?= /* @noEscape */
            $code; ?>" style="display: none;">
    <div class="field type required">
        <label for="<?= /* @noEscape */
        $code; ?>_cc_type" class="label">
            <span><?= $escaper->escapeHtml(__('Credit Card Type')); ?></span>
        </label>
        <div class="control">
            <select id="<?= /* @noEscape */
            $code; ?>_cc_type"
                    data-mage-init='{
                        "creditCardType":{"creditCardTypeContainer":"#<?= /* @noEscape */
                        $code; ?>_cc_type_ss_div"}
                    }'
                    name="payment[cc_type]" data-validate='{
                        required:true,
                        "validate-cc-type-select":"#<?= /* @noEscape */
                        $code; ?>_cc_number"
                    }'
                    class="select">
                <option value=""><?= $escaper->escapeHtml(__('--Please Select--')); ?></option>
                <?php foreach ($block->getCcAvailableTypes() as $typeCode => $typeName): ?>
                    <option value="<?= $escaper->escapeHtml($typeCode); ?>"
                            <?php if ($typeCode == $ccType): ?> selected="selected"<?php endif; ?>>
                        <?= $escaper->escapeHtml($typeName); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="field number required">
        <label for="<?= /* @noEscape */
        $code; ?>_cc_number" class="label">
            <span><?= $escaper->escapeHtml(__('Credit Card Number')); ?></span>
        </label>
        <div class="control">
            <input type="number" id="<?= /* @noEscape */
            $code; ?>_cc_number" name="payment[cc_number]"
                   title="<?= $escaper->escapeHtml(__('Credit Card Number')); ?>" class="input-text" value=""
                   data-validate='{
                       "required-number":true,
                       "validate-cc-number":"#<?= /* @noEscape */
                        $code; ?>_cc_type",
                       "validate-cc-type":"#<?= /* @noEscape */
                        $code; ?>_cc_type"
                   }'/>
        </div>
    </div>
    <div class="field date required" id="<?= /* @noEscape */
    $code; ?>_cc_type_exp_div">
        <label for="<?= /* @noEscape */
        $code; ?>_expiration" class="label">
            <span><?= $escaper->escapeHtml(__('Expiration Date')); ?></span>
        </label>
        <div class="control">
            <div class="fields group group-2">
                <div class="field no-label month">
                    <div class="control">
                        <select id="<?= /* @noEscape */
                        $code; ?>_expiration" name="payment[cc_exp_month]" class="select month"
                                data-validate='{required:true, "validate-cc-exp":"#<?= /* @noEscape */
                                $code; ?>_expiration_yr"}'>
                            <?php foreach ($block->getCcMonths() as $k => $v): ?>
                                <option value="<?= /* @noEscape */
                                $k ? $escaper->escapeHtml($k) : ''; ?>"
                                        <?php if ($k == $ccExpMonth): ?> selected="selected"<?php endif; ?>>
                                    <?= $escaper->escapeHtml($v); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="field no-label year">
                    <div class="control">
                        <select id="<?= /* @noEscape */
                        $code; ?>_expiration_yr" name="payment[cc_exp_year]"
                                class="select year" data-validate='{required:true}'>
                            <?php foreach ($block->getCcYears() as $k => $v): ?>
                                <option value="<?= /* @noEscape */
                                $k ? $escaper->escapeHtml($k) : ''; ?>
                                "<?php if ($k == $ccExpYear): ?> selected="selected"<?php endif; ?>>
                                    <?= $escaper->escapeHtml($v); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php if ($block->hasVerification()): ?>
        <div class="field cvv required" id="<?= /* @noEscape */
        $code; ?>_cc_type_cvv_div">
            <label for="<?= /* @noEscape */
            $code; ?>_cc_cid" class="label">
                <span><?= $escaper->escapeHtml(__('Card Verification Number')); ?></span>
            </label>
            <div class="control">
                <input type="number" title="<?= $escaper->escapeHtml(__('Card Verification Number')); ?>"
                       class="input-text cvv" id="<?= /* @noEscape */
                        $code; ?>_cc_cid" name="payment[cc_cid]" value=""
                       data-validate='{"validate-cc-cvn":"#<?= /* @noEscape */
                        $code; ?>_cc_type"}'/>
                <?php $content = '<img src=\"' . $block->getViewFileUrl('Magento_Checkout::cvv.png') . '\" alt=\"' .
                        $escaper->escapeHtml(__('Card Verification Number Visual Reference')) .
                        '\" title=\"' .
                        $escaper->escapeHtml(__('Card Verification Number Visual Reference')) . '\" />'; ?>
                <div class="note">
                    <a href="#" class="action cvv" title="<?= $escaper->escapeHtml(__('What is this?')); ?>"
                       data-mage-init='{"tooltip": {"content": "<?= /* @noEscape */
                        $content; ?>"}}'>
                        <span><?= $escaper->escapeHtml(__('What is this?')); ?></span>
                    </a>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($block->hasSsCardType()): ?>
        <div class="field switch solo required" id="<?= /* @noEscape */
        $code; ?>_cc_type_ss_div">
            <div class="nested">
                <div class="field switch solo required">
                    <label for="<?= /* @noEscape */
                    $code; ?>_cc_issue" class="label">
                        <span><?= $escaper->escapeHtml(__('Switch/Solo/Maestro Only')); ?></span>
                    </label>
                </div>
                <div class="field number required">
                    <label for="<?= /* @noEscape */
                    $code; ?>_cc_issue" class="label">
                        <span><?= $escaper->escapeHtml(__('Issue Number')); ?></span>
                    </label>
                    <div class="control">
                        <input type="text" title="<?= $escaper->escapeHtml(__('Issue Number')); ?>"
                               class="input-text cvv"
                               id="<?= /* @noEscape */
                                $code; ?>_cc_issue" name="payment[cc_ss_issue]" value=""
                               data-validate='{"validate-cc-ukss":true}'/>
                    </div>
                </div>

                <div class="field date required">
                    <label for="<?= /* @noEscape */
                    $code; ?>_start_month" class="label">
                        <span><?= $escaper->escapeHtml(__('Start Date')); ?></span>
                    </label>
                    <div class="control">
                        <div class="fields group group-2">
                            <div class="field no-label">
                                <div class="control">
                                    <select id="<?= /* @noEscape */
                                    $code; ?>_start_month" name="payment[cc_ss_start_month]"
                                            class="select month" data-validate='{"validate-cc-ukss":true}'>
                                        <?php foreach ($block->getCcMonths() as $k => $v): ?>
                                            <option value="<?= /* @noEscape */
                                            $k ? $escaper->escapeHtml($k) : ''; ?>"
                                                    <?php if ($k == $block->getInfoData('cc_ss_start_month')): ?>
                                                        selected="selected"
                                                    <?php endif; ?>>
                                                <?= $escaper->escapeHtml($v); ?>
                                            </option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>
                            <div class="field no-label">
                                <div class="control">
                                    <select id="<?= /* @noEscape */
                                    $code; ?>_start_year"
                                            name="payment[cc_ss_start_year]" class="select year"
                                            data-validate='{"validate-cc-ukss":true}'>
                                        <?php foreach ($block->getSsStartYears() as $k => $v): ?>
                                            <option value="<?= /* @noEscape */
                                            $k ? $escaper->escapeHtml($k) : ''; ?>"
                                                    <?php if ($k == $block->getInfoData('cc_ss_start_year')): ?>
                                                        selected="selected"
                                                    <?php endif; ?>>
                                                <?= $escaper->escapeHtml($v); ?>
                                            </option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="adv container" data-validation-msg="validate-cc-ukss">&nbsp;</div>
            </div>
        </div>
    <?php endif; ?>
    <?= $block->getChildHtml() ?>
</fieldset>
