<?php
$hostedFieldsSdk = $block->getJsSrcHostedFields();
$sdkUrl = $hostedFieldsSdk['sdkUrl'];
$integrityHash = $hostedFieldsSdk['integrityHash'];
?>
<?php if ($integrityHash): ?>
<script src="<?= $escaper->escapeUrl($sdkUrl); ?>"
        type="text/javascript"
        charset="utf-8"
        integrity="<?= $escaper->escapeHtmlAttr($integrityHash); ?>"
        crossorigin="anonymous"></script>
<?php else: ?>
<script src="<?= $escaper->escapeUrl($sdkUrl); ?>" type="text/javascript" charset="utf-8"></script>
<?php endif; ?>
